spring:
  profiles:
    active: local
  cloud:
    aws:
      sqs:
        queue:
          email-alert: ${SQS_EMAIL_ALERT_QUEUE_URL}
      region:
        static: ap-northeast-2
      credentials:
        instance-profile: true