spring.application.name=plus-project

#MySQL setting
spring.datasource.url=jdbc:mysql://localhost:3306/delicou
spring.datasource.username=root
spring.datasource.password=1478

#JWT secret key
jwt.secret.key=HULfUlHgYuvQ0YIl9qHyQ0Fq4gZb5ZofLD0isNs7Xb+2FBsrs8HMUQpGyJTEcMNb2vott/0TtiuMkvIcmc/fYg==