#AWS SQS
spring:
  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        instance-profile: true
      sqs:
        queue:
          emailAlert: couponmoa-queue
          couponAlert: coupon-alert-queue
      s3:
        bucket: couponmoa-user-profile


  #RDB setting
  datasource:
    url: ${MYSQL_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  #Redis setting
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

#JWT
jwt:
  secret:
    key: ${JWT_SECRET_KEY}

#server setting
server:
  port: 8080
  address: 0.0.0.0

#server health check
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always