spring:
  profiles:
    active: local
  cloud:
    aws:
      sqs:
        queue:
          email-alert: https://sqs.ap-northeast-2.amazonaws.com/588738590244/couponmoa-queue
      region:
        static: ap-northeast-2
      credentials:
        instance-profile: true