spring:
  application:
    name: couponmoa
    elasticsearch:
      uris: http://elasticsearch:9200
      google:
        api:
          key: ${GOOGLE_API_KEY}
  profiles:
    active: local

server:
  tomcat:
    mbeanregistry:
      enabled: true