spring.application.name=couponmoa
spring.profiles.active=local

#JPA setting
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# ?? actuator? ?? ???? ??? ????.
management.endpoints.web.exposure.include=*

# env, beans? ??
management.endpoints.web.exposure.exclude=env,beans
management.endpoint.health.show-details=always

#????? port = 8081
management.server.port=8081

# JobRunr
org.jobrunr.dashboard.enabled=true
org.jobrunr.background-job-server.enabled=true
org.jobrunr.jobs.metrics.enabled=true